version: "3.8"

services:
  mysql_test_db_001:
    container_name: mysql_test_db_001
    image: ghcr.io/joseesco24/mysql_test_db_001:latest
    networks:
      - testing_databases_network
    ports:
      - target: 3306
        published: 3308
        protocol: tcp
    volumes:
      - type: volume
        source: mysql_test_db_001_disc
        target: /var/lib/mysql

  postgres_test_db_001:
    container_name: postgres_test_db_001
    image: ghcr.io/joseesco24/postgres_test_db_001:latest
    networks:
      - testing_databases_network
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_test_db_001_disc
        target: /var/lib/postgresql/data

networks:
  testing_databases_network:
    name: testing_databases_network
    external: false
    driver: bridge

volumes:
  postgres_test_db_001_disc:
  mysql_test_db_001_disc:
