version: "3.8"

services:
  postgresql_test_db_001:
    container_name: postgresql_test_db_001
    image: ghcr.io/joseesco24/postgresql_test_db_001:latest
    networks:
      - testing_databases_network
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - type: volume
        source: postgresql_test_db_001_disc
        target: /var/lib/postgresql/data

networks:
  testing_databases_network:
    name: testing_databases_network
    external: false
    driver: bridge

volumes:
  postgresql_test_db_001_disc:
